// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWIBP2SgMH3JtcUomnR32JxZ27xSFLUc',
    appId: '1:1049848499302:web:f3b6a1905bff33a0ff71a7',
    messagingSenderId: '1049848499302',
    projectId: 'vantra-cace2',
    authDomain: 'vantra-cace2.firebaseapp.com',
    storageBucket: 'vantra-cace2.firebasestorage.app',
    measurementId: 'G-JK1ESC0B0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEo1d2GAc6SXT_iw3NCvILe21KUfB0_k',
    appId: '1:1049848499302:android:93238e3db0998f48ff71a7',
    messagingSenderId: '1049848499302',
    projectId: 'vantra-cace2',
    storageBucket: 'vantra-cace2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_vEQ-5BWp-IuryBqbQL_I8WVSg56zQs',
    appId: '1:1049848499302:ios:606aa467bfa3febaff71a7',
    messagingSenderId: '1049848499302',
    projectId: 'vantra-cace2',
    storageBucket: 'vantra-cace2.firebasestorage.app',
    iosBundleId: 'com.example.vantraMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_vEQ-5BWp-IuryBqbQL_I8WVSg56zQs',
    appId: '1:1049848499302:ios:606aa467bfa3febaff71a7',
    messagingSenderId: '1049848499302',
    projectId: 'vantra-cace2',
    storageBucket: 'vantra-cace2.firebasestorage.app',
    iosBundleId: 'com.example.vantraMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWIBP2SgMH3JtcUomnR32JxZ27xSFLUc',
    appId: '1:1049848499302:web:ba9d2d46f35367e6ff71a7',
    messagingSenderId: '1049848499302',
    projectId: 'vantra-cace2',
    authDomain: 'vantra-cace2.firebaseapp.com',
    storageBucket: 'vantra-cace2.firebasestorage.app',
    measurementId: 'G-54QFWZB5JM',
  );
}

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
